#ifndef MOVEO_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_
#define MOVEO_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define MOVEO_HARDWARE_INTERFACE_EXPORT __attribute__ ((dllexport))
    #define MOVEO_HARDWARE_INTERFACE_IMPORT __attribute__ ((dllimport))
  #else
    #define MOVEO_HARDWARE_INTERFACE_EXPORT __declspec(dllexport)
    #define MOVEO_HARDWARE_INTERFACE_IMPORT __declspec(dllimport)
  #endif
  #ifdef MOVEO_HARDWARE_INTERFACE_BUILDING_DLL
    #define MOVEO_HARDWARE_INTERFACE_PUBLIC MOVEO_HARDWARE_INTERFACE_EXPORT
  #else
    #define MOVEO_HARDWARE_INTERFACE_PUBLIC MOVEO_HARDWARE_INTERFACE_IMPORT
  #endif
  #define MOVEO_HARDWARE_INTERFACE_PUBLIC_TYPE MOVEO_HARDWARE_INTERFACE_PUBLIC
  #define MOVEO_HARDWARE_INTERFACE_LOCAL
#else
  #define MOVEO_HARDWARE_INTERFACE_EXPORT __attribute__ ((visibility("default")))
  #define MOVEO_HARDWARE_INTERFACE_IMPORT
  #if __GNUC__ >= 4
    #define MOVEO_HARDWARE_INTERFACE_PUBLIC __attribute__ ((visibility("default")))
    #define MOVEO_HARDWARE_INTERFACE_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define MOVEO_HARDWARE_INTERFACE_PUBLIC
    #define MOVEO_HARDWARE_INTERFACE_LOCAL
  #endif
  #define MOVEO_HARDWARE_INTERFACE_PUBLIC_TYPE
#endif

#endif  // MOVEO_HARDWARE_INTERFACE__VISIBILITY_CONTROL_H_
